name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install python
      run: apt install python3 python3-pip
    - name: install conan
      run: pip3 install conan
    - name: configure
      run: mkdir build && cd build && cmake .. -DBUILD_TESTS=ON
    - name: build
      run: cmake --build .
    - name: test
      run: ctest
