name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install python
      run: sudo apt install python3 python3-pip
    - name: install conan
      run: pip3 install conan
    - name: update conan profile
      run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
    - name: install dependencies
      run: conan install .
    - name: configure
      run: cmake . -DBUILD_TESTS=ON
    - name: build
      run: cmake --build .
    - name: test
      run: ctest
